#!/usr/bin/env python3
"""Seed the Open WebUI admin user if none exists yet.

Reads credentials from environment variables (set via .env):
  WEBUI_ADMIN_EMAIL    (default: admin@localhost)
  WEBUI_ADMIN_PASSWORD (required — generated by make config)
  WEBUI_PORT           (default: 3001)
"""

import json
import os
import sys
import time
import urllib.error
import urllib.request

WEBUI_PORT = os.environ.get("WEBUI_PORT", "3001")
WEBUI_URL = f"http://localhost:{WEBUI_PORT}"
ADMIN_NAME = os.environ.get("WEBUI_ADMIN_NAME", "Admin")
ADMIN_EMAIL = os.environ.get("WEBUI_ADMIN_EMAIL", "admin@localhost")
ADMIN_PASSWORD = os.environ.get("WEBUI_ADMIN_PASSWORD", "")

MAX_RETRIES = 30
RETRY_INTERVAL = 2


def webui_ready() -> bool:
    try:
        req = urllib.request.Request(f"{WEBUI_URL}/api/v1/auths/signin", method="POST")
        req.add_header("Content-Type", "application/json")
        data = json.dumps({"email": "probe@probe", "password": "x"}).encode()
        urllib.request.urlopen(req, data, timeout=5)
        return True
    except urllib.error.HTTPError:
        return True
    except (urllib.error.URLError, OSError):
        return False


def user_exists() -> bool:
    try:
        req = urllib.request.Request(f"{WEBUI_URL}/api/v1/auths/signin", method="POST")
        req.add_header("Content-Type", "application/json")
        data = json.dumps({"email": ADMIN_EMAIL, "password": ADMIN_PASSWORD}).encode()
        resp = urllib.request.urlopen(req, data, timeout=5)
        return resp.status == 200
    except urllib.error.HTTPError:
        return False
    except (urllib.error.URLError, OSError):
        return False


def create_admin() -> bool:
    try:
        req = urllib.request.Request(f"{WEBUI_URL}/api/v1/auths/signup", method="POST")
        req.add_header("Content-Type", "application/json")
        data = json.dumps({
            "name": ADMIN_NAME,
            "email": ADMIN_EMAIL,
            "password": ADMIN_PASSWORD,
        }).encode()
        resp = urllib.request.urlopen(req, data, timeout=10)
        result = json.loads(resp.read())
        if result.get("id"):
            return True
        return False
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        if "already" in body.lower() or "permission" in body.lower():
            return True
        print(f"  Signup failed: {e.code} — {body}", file=sys.stderr)
        return False
    except (urllib.error.URLError, OSError) as e:
        print(f"  Connection error: {e}", file=sys.stderr)
        return False


def main() -> int:
    if not ADMIN_PASSWORD:
        print("WEBUI_ADMIN_PASSWORD not set in .env — skipping admin seed.", file=sys.stderr)
        print("Run: make config  (generates all secrets including WebUI admin)", file=sys.stderr)
        return 1

    print(f"Seeding Open WebUI admin ({ADMIN_EMAIL})...")
    for i in range(MAX_RETRIES):
        if webui_ready():
            break
        time.sleep(RETRY_INTERVAL)
    else:
        print("ERROR: Open WebUI not reachable after 60s", file=sys.stderr)
        return 1

    if user_exists():
        print(f"Admin already exists ({ADMIN_EMAIL})")
        return 0

    if create_admin():
        print(f"Created admin: {ADMIN_EMAIL}")
        return 0

    print("Could not create admin — signup may be disabled (admin already exists).", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
